-- MySQL Script generated by MySQL Workbench
-- Fri Apr  4 22:49:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tipo Manutenção`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo Manutenção` (
  `idTipo Manutenção` INT NOT NULL,
  `Tipo Manutençãocol` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo Manutenção`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe_Mecânico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe_Mecânico` (
  `idEquipe_Mecânico` INT NOT NULL,
  `Especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipe_Mecânico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veículo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veículo` (
  `idVeículo` INT NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  `Fabricante` VARCHAR(45) NULL,
  `Placa` VARCHAR(45) NULL,
  `Km` FLOAT NULL,
  `Cor` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVeículo`, `Cliente_idCliente`),
  INDEX `fk_Veículo_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Veículo_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `Data de Emissão` DATE NULL,
  `Data de Entrega` DATE NULL,
  `Valor` FLOAT NULL,
  `Status` VARCHAR(45) NULL,
  `Tipo Manutenção_idTipo Manutenção` INT NOT NULL,
  `Equipe_Mecânico_idEquipe_Mecânico` INT NOT NULL,
  `Veículo_idVeículo` INT NOT NULL,
  `Veículo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOrdem de Serviço`, `Tipo Manutenção_idTipo Manutenção`, `Equipe_Mecânico_idEquipe_Mecânico`, `Veículo_idVeículo`, `Veículo_Cliente_idCliente`),
  INDEX `fk_Ordem de Serviço_Tipo Manutenção1_idx` (`Tipo Manutenção_idTipo Manutenção` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Equipe_Mecânico1_idx` (`Equipe_Mecânico_idEquipe_Mecânico` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Veículo1_idx` (`Veículo_idVeículo` ASC, `Veículo_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Tipo Manutenção1`
    FOREIGN KEY (`Tipo Manutenção_idTipo Manutenção`)
    REFERENCES `mydb`.`Tipo Manutenção` (`idTipo Manutenção`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Equipe_Mecânico1`
    FOREIGN KEY (`Equipe_Mecânico_idEquipe_Mecânico`)
    REFERENCES `mydb`.`Equipe_Mecânico` (`idEquipe_Mecânico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Veículo1`
    FOREIGN KEY (`Veículo_idVeículo` , `Veículo_Cliente_idCliente`)
    REFERENCES `mydb`.`Veículo` (`idVeículo` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecânico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecânico` (
  `idMecânico` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  `Equipe_Mecânico_idEquipe_Mecânico` INT NOT NULL,
  PRIMARY KEY (`idMecânico`, `Equipe_Mecânico_idEquipe_Mecânico`),
  INDEX `fk_Mecânico_Equipe_Mecânico1_idx` (`Equipe_Mecânico_idEquipe_Mecânico` ASC) VISIBLE,
  CONSTRAINT `fk_Mecânico_Equipe_Mecânico1`
    FOREIGN KEY (`Equipe_Mecânico_idEquipe_Mecânico`)
    REFERENCES `mydb`.`Equipe_Mecânico` (`idEquipe_Mecânico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` FLOAT NULL,
  PRIMARY KEY (`idServiço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peça` (
  `idPeça` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` FLOAT NULL,
  PRIMARY KEY (`idPeça`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço Realizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço Realizado` (
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  `Ordem de Serviço_Equipe_Mecânico_idEquipe_Mecânico` INT NOT NULL,
  `Serviço_idServiço` INT NOT NULL,
  `Autorização` VARCHAR(45) NULL,
  `Serviço Realizadocol` TINYINT NULL,
  PRIMARY KEY (`Ordem de Serviço_idOrdem de Serviço`, `Ordem de Serviço_Equipe_Mecânico_idEquipe_Mecânico`, `Serviço_idServiço`),
  INDEX `fk_Ordem de Serviço_has_Serviço_Serviço1_idx` (`Serviço_idServiço` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_has_Serviço_Ordem de Serviço1_idx` (`Ordem de Serviço_idOrdem de Serviço` ASC, `Ordem de Serviço_Equipe_Mecânico_idEquipe_Mecânico` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_has_Serviço_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço` , `Ordem de Serviço_Equipe_Mecânico_idEquipe_Mecânico`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço` , `Equipe_Mecânico_idEquipe_Mecânico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_has_Serviço_Serviço1`
    FOREIGN KEY (`Serviço_idServiço`)
    REFERENCES `mydb`.`Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peças do Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peças do Serviço` (
  `Peça_idPeça` INT NOT NULL,
  `Serviço Realizado_Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  `Serviço Realizado_Ordem de Serviço_Equipe_Mecânico_idEquipe_Mecânico` INT NOT NULL,
  `Serviço Realizado_Serviço_idServiço` INT NOT NULL,
  `Quantidade Peça` FLOAT NULL,
  PRIMARY KEY (`Peça_idPeça`, `Serviço Realizado_Ordem de Serviço_idOrdem de Serviço`, `Serviço Realizado_Ordem de Serviço_Equipe_Mecânico_idEquipe_Mecânico`, `Serviço Realizado_Serviço_idServiço`),
  INDEX `fk_Peça_has_Serviço Realizado_Serviço Realizado1_idx` (`Serviço Realizado_Ordem de Serviço_idOrdem de Serviço` ASC, `Serviço Realizado_Ordem de Serviço_Equipe_Mecânico_idEquipe_Mecânico` ASC, `Serviço Realizado_Serviço_idServiço` ASC) VISIBLE,
  INDEX `fk_Peça_has_Serviço Realizado_Peça1_idx` (`Peça_idPeça` ASC) VISIBLE,
  CONSTRAINT `fk_Peça_has_Serviço Realizado_Peça1`
    FOREIGN KEY (`Peça_idPeça`)
    REFERENCES `mydb`.`Peça` (`idPeça`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peça_has_Serviço Realizado_Serviço Realizado1`
    FOREIGN KEY (`Serviço Realizado_Ordem de Serviço_idOrdem de Serviço` , `Serviço Realizado_Ordem de Serviço_Equipe_Mecânico_idEquipe_Mecânico` , `Serviço Realizado_Serviço_idServiço`)
    REFERENCES `mydb`.`Serviço Realizado` (`Ordem de Serviço_idOrdem de Serviço` , `Ordem de Serviço_Equipe_Mecânico_idEquipe_Mecânico` , `Serviço_idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
